name: Docker Fullstack CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2️⃣ Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        # Fail the job if login fails
        continue-on-error: false

      # 4️⃣ Build and push backend image
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend-practice
          file: ./backend-practice/backend.Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/docker-backend2:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/docker-backend2:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/docker-backend2:latest
          cache-to: type=registry,mode=max,ref=${{ secrets.DOCKERHUB_USERNAME }}/docker-backend2:cache

      # 5️⃣ Build and push frontend image
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend-practice
          file: ./frontend-practice/frontend.Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/docker-frontend2:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/docker-frontend2:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/docker-frontend2:latest
          cache-to: type=registry,mode=max,ref=${{ secrets.DOCKERHUB_USERNAME }}/docker-frontend2:cache
